right_leg_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - r_hip_yaw
    - r_hip_roll
    - r_hip_pitch
    - r_knee_pitch
    - r_ankle_pitch
    - r_ankle_roll
  constraints:
    goal_time: &goal_time_constraint 0.6
    r_hip_yaw:
      goal: &goal_pos_constraint 0.02
    r_hip_roll:
      goal: *goal_pos_constraint
    r_hip_pitch:
      goal: *goal_pos_constraint
    r_knee_pitch:
      goal: *goal_pos_constraint
    r_ankle_pitch:
      goal: *goal_pos_constraint
    r_ankle_roll:
      goal: *goal_pos_constraint

  stop_trajectory_duration: 0.0


left_leg_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - l_hip_yaw
    - l_hip_roll
    - l_hip_pitch
    - l_knee_pitch
    - l_ankle_pitch
    - l_ankle_roll
  constraints:
    goal_time: *goal_time_constraint
    l_hip_yaw:
      goal: *goal_pos_constraint
    l_hip_roll:
      goal: *goal_pos_constraint
    l_hip_pitch:
      goal: *goal_pos_constraint
    l_knee_pitch:
      goal: *goal_pos_constraint
    l_ankle_pitch:
      goal: *goal_pos_constraint
    l_ankle_roll:
      goal: *goal_pos_constraint

  stop_trajectory_duration: 0.0


torso_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - waist_yaw
    - waist_pitch
  constraints:
    goal_time: *goal_time_constraint
    waist_yaw:
      goal: *goal_pos_constraint
    waist_pitch:
      goal: *goal_pos_constraint

  stop_trajectory_duration: 0.0

right_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - r_shoulder_pitch
    - r_shoulder_roll
    - r_shoulder_yaw
    - r_elbow_pitch
    - r_wrist_yaw
    - r_wrist_pitch
  constraints:
    goal_time: *goal_time_constraint
    r_shoulder_pitch:
      goal: *goal_pos_constraint
    r_shoulder_roll:
      goal: *goal_pos_constraint
    r_shoulder_yaw:
      goal: *goal_pos_constraint
    r_elbow_pitch:
      goal: *goal_pos_constraint
    r_wrist_yaw:
      goal: *goal_pos_constraint
    r_wrist_pitch:
      goal: *goal_pos_constraint

  stop_trajectory_duration: 0.0


left_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - l_shoulder_pitch
    - l_shoulder_roll
    - l_shoulder_yaw
    - l_elbow_pitch
    - l_wrist_yaw
    - l_wrist_pitch
  constraints:
    goal_time: *goal_time_constraint
    l_shoulder_pitch:
      goal: *goal_pos_constraint
    l_shoulder_roll:
      goal: *goal_pos_constraint
    l_shoulder_yaw:
      goal: *goal_pos_constraint
    l_elbow_pitch:
      goal: *goal_pos_constraint
    l_wrist_yaw:
      goal: *goal_pos_constraint
    l_wrist_pitch:
      goal: *goal_pos_constraint

  stop_trajectory_duration: 0.0