teo:

 #-----------------------------------
 # Publish all joint states 
 #-----------------------------------
  joint_state_controller:
     type: joint_state_controller/JointStateController
     publish_rate: 50 

  # ----------------------
  # Position Controllers #
  # ----------------------

  # Waist
  waist_yaw_position_controller:
    type: position_controllers/JointPositionController
    joint: waist_yaw
    pid: {p: 10000, i: 10, d: 1}
  waist_pitch_position_controller:
    type: position_controllers/JointPositionController
    joint: waist_pitch
    pid: {p: 10000, i: 10, d: 1}

  # Right Leg
  r_hip_yaw_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: r_hip_yaw
    pid: {p: 3000.0, i: 10, d: 1}
  r_hip_roll_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: r_hip_roll
    pid: {p: 3000, i: 10, d: 1}
  r_hip_pitch_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: r_hip_pitch
    pid: {p: 3000, i: 10, d: 1}
  r_knee_pitch_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: r_knee_pitch
    pid: {p: 3000, i: 10, d: 1}
  r_ankle_pitch_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: r_ankle_pitch
    pid: {p: 3000, i: 10, d: 1}
  r_ankle_roll_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: r_ankle_roll
    pid: {p: 3000, i: 10, d: 1}

  # Left leg
  l_hip_yaw_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: l_hip_yaw
    pid: {p: 3000, i: 10, d: 1}
  l_hip_roll_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: l_hip_roll
    pid: {p: 3000, i: 10, d: 1}
  l_hip_pitch_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: l_hip_pitch
    pid: {p: 3000, i: 10, d: 1}
  l_knee_pitch_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: l_knee_pitch
    pid: {p: 3000, i: 10, d: 1}
  l_ankle_pitch_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: l_ankle_pitch
    pid: {p: 3000, i: 10, d: 1}
  l_ankle_roll_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: l_ankle_roll
    pid: {p: 3000, i: 10, d: 1}

  # Right Arm
  r_shoulder_pitch_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: r_shoulder_pitch
    pid: {p: 3000, i: 5, d: 1}
  r_shoulder_roll_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: r_shoulder_roll
    pid: {p: 3000, i: 5, d: 1}
  r_shoulder_yaw_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: r_shoulder_yaw
    pid: {p: 3000, i: 5, d: 1}
  r_elbow_pitch_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: r_elbow_pitch
    pid: {p: 3000, i: 5, d: 1}
  r_wrist_yaw_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: r_wrist_yaw
    pid: {p: 500, i: 5, d: 1}
  r_wrist_pitch_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: r_wrist_pitch
    pid: {p: 500, i: 5, d: 1}

  # Left Arm
  l_shoulder_pitch_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: l_shoulder_pitch
    pid: {p: 3000, i: 5, d: 1}
  l_shoulder_roll_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: l_shoulder_roll
    pid: {p: 3000, i: 5, d: 1}
  l_shoulder_yaw_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: l_shoulder_yaw
    pid: {p: 3000, i: 5, d: 1}
  l_elbow_pitch_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: l_elbow_pitch
    pid: {p: 3000, i: 5, d: 1}
  l_wrist_yaw_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: l_wrist_yaw
    pid: {p: 500, i: 5, d: 1}
  l_wrist_pitch_position_controller:
    type: position_controllers/JointPositionController
    # type: effort_controllers/JointVelocityController
    # type: effort_controllers/JointEffortController
    joint: l_wrist_pitch
    pid: {p: 500, i: 5, d: 1}
